server:
  port: 8082

spring:
  application:
    name: pay

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://travel_mysql:3306/travel_pay?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r@@

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8000/eureka/

user-service:
  url: http://10.178.0.4:8080
  
travel-service:
  url: http://10.178.0.4:8081

kakaopay:
  cid: TC0ONETIME
  approval-url: http://localhost/api/v1/pay/deposit/success
  fail-url: http://localhost/api/v1/pay/deposit/fail
  cancel-url: http://localhost/api/v1/pay/deposit/refund
  item-name: "여행참여 보증금"
  quantity: 1
  deposit-amount: 100000
  tax-free-amount: 9090
  secret-key: DEVBB2EC55AEA5209485B283C6EAC15502C4B307

