FROM openjdk:17
EXPOSE 7070
RUN mkdir -p deploy
WORKDIR /deploy
COPY gateway/build/libs/gateway-0.0.1-SNAPSHOT.jar api.jar
ENTRYPOINT ["java", "-jar", "/deploy/api.jar", "--spring.profiles.active=dev"]