package com.zerobase.travel.communities.type;

public enum ErrorCode {

    PARTICIPATION_NOT_FOUND, PARTICIPATION_LOCK, COMMUNITY_NON_EXISTENT,
    PARTICIPATION_LIMIT, PARTICIPATION_STATUS_ERROR;

}
