package com.zerobase.travel.communities.type;

public enum ErrorCode {

    PARTICIPATION_LIMIT, COMMUNITY_NON_EXISTENT,
    PARTICIPATION_NOT_FOUND, COMMUNITY_NON_EXISTENT, PARTICIPATION_STATUS_ERROR;
}
