
### Create Participation (POST Request)
POST http://localhost:8081/api/v1/posts/1/participations
userId: userId
Content-Type: application/json


### Get Participation List (GET Request)
GET http://localhost:8081/api/v1/posts/1234/participations
Accept: application/json

### Delete Participation (GET Placeholder - Replace with DELETE later if implemented)
GET http://localhost:8081/api/v1/posts/1234/participations/1
Accept: application/json