### GET request with a header
POST http://localhost:8081/api/v1/posts/1/participations
Content-Type: application/json

{
  "userId": "userid"
}


###
GET http://localhost:8081/api/v1/posts/1234/participations
Accept: application/json

