server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/users/**, /login, /logout,
        - id: second-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/posts/**, /api/v1/reviews, /api/v1/communities, /api/v1/file
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/