name: Java CI with Gradle

on:
  push:
    branches:
      - develop-githubCI # Replace with your desired branch name
  pull_request:
    branches:
      - develop-githubCI  # Replace with your desired branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests and generate code coverage
        run: ./gradlew test jacocoTestReport --continue

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/index.html
